apiVersion: v1
kind: Service
metadata:
  name: python-random-service
spec:
  selector:
    app: python-random
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30080  